import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer/page";
// import Navbar from "./components/navigation/navbar";



export const metadata = {
  title: "Weather App 🌤",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <div className="mt-2">
          {children}
          </div>
          <Footer />
          </body>
    </html>
  );
}
